// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: expanse/protos/expanse.proto

package expanse

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExpanseService_GetExpansesAmountInCurrentMonth_FullMethodName = "/expanse.ExpanseService/GetExpansesAmountInCurrentMonth"
)

// ExpanseServiceClient is the client API for ExpanseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExpanseServiceClient interface {
	GetExpansesAmountInCurrentMonth(ctx context.Context, in *GetExpansesAmountInCurrentMonthRequest, opts ...grpc.CallOption) (*GetExpansesAmountInCurrentMonthResponse, error)
}

type expanseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExpanseServiceClient(cc grpc.ClientConnInterface) ExpanseServiceClient {
	return &expanseServiceClient{cc}
}

func (c *expanseServiceClient) GetExpansesAmountInCurrentMonth(ctx context.Context, in *GetExpansesAmountInCurrentMonthRequest, opts ...grpc.CallOption) (*GetExpansesAmountInCurrentMonthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpansesAmountInCurrentMonthResponse)
	err := c.cc.Invoke(ctx, ExpanseService_GetExpansesAmountInCurrentMonth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExpanseServiceServer is the server API for ExpanseService service.
// All implementations must embed UnimplementedExpanseServiceServer
// for forward compatibility.
type ExpanseServiceServer interface {
	GetExpansesAmountInCurrentMonth(context.Context, *GetExpansesAmountInCurrentMonthRequest) (*GetExpansesAmountInCurrentMonthResponse, error)
	mustEmbedUnimplementedExpanseServiceServer()
}

// UnimplementedExpanseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExpanseServiceServer struct{}

func (UnimplementedExpanseServiceServer) GetExpansesAmountInCurrentMonth(context.Context, *GetExpansesAmountInCurrentMonthRequest) (*GetExpansesAmountInCurrentMonthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExpansesAmountInCurrentMonth not implemented")
}
func (UnimplementedExpanseServiceServer) mustEmbedUnimplementedExpanseServiceServer() {}
func (UnimplementedExpanseServiceServer) testEmbeddedByValue()                        {}

// UnsafeExpanseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExpanseServiceServer will
// result in compilation errors.
type UnsafeExpanseServiceServer interface {
	mustEmbedUnimplementedExpanseServiceServer()
}

func RegisterExpanseServiceServer(s grpc.ServiceRegistrar, srv ExpanseServiceServer) {
	// If the following call pancis, it indicates UnimplementedExpanseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExpanseService_ServiceDesc, srv)
}

func _ExpanseService_GetExpansesAmountInCurrentMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpansesAmountInCurrentMonthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpanseServiceServer).GetExpansesAmountInCurrentMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpanseService_GetExpansesAmountInCurrentMonth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpanseServiceServer).GetExpansesAmountInCurrentMonth(ctx, req.(*GetExpansesAmountInCurrentMonthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExpanseService_ServiceDesc is the grpc.ServiceDesc for ExpanseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExpanseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "expanse.ExpanseService",
	HandlerType: (*ExpanseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExpansesAmountInCurrentMonth",
			Handler:    _ExpanseService_GetExpansesAmountInCurrentMonth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expanse/protos/expanse.proto",
}
