// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: expanse/protos/expanse.proto

package expanse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExpansesAmountInCurrentMonthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetExpansesAmountInCurrentMonthRequest) Reset() {
	*x = GetExpansesAmountInCurrentMonthRequest{}
	mi := &file_expanse_protos_expanse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpansesAmountInCurrentMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpansesAmountInCurrentMonthRequest) ProtoMessage() {}

func (x *GetExpansesAmountInCurrentMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expanse_protos_expanse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpansesAmountInCurrentMonthRequest.ProtoReflect.Descriptor instead.
func (*GetExpansesAmountInCurrentMonthRequest) Descriptor() ([]byte, []int) {
	return file_expanse_protos_expanse_proto_rawDescGZIP(), []int{0}
}

func (x *GetExpansesAmountInCurrentMonthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetExpansesAmountInCurrentMonthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount float32 `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetExpansesAmountInCurrentMonthResponse) Reset() {
	*x = GetExpansesAmountInCurrentMonthResponse{}
	mi := &file_expanse_protos_expanse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpansesAmountInCurrentMonthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpansesAmountInCurrentMonthResponse) ProtoMessage() {}

func (x *GetExpansesAmountInCurrentMonthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expanse_protos_expanse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpansesAmountInCurrentMonthResponse.ProtoReflect.Descriptor instead.
func (*GetExpansesAmountInCurrentMonthResponse) Descriptor() ([]byte, []int) {
	return file_expanse_protos_expanse_proto_rawDescGZIP(), []int{1}
}

func (x *GetExpansesAmountInCurrentMonthResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_expanse_protos_expanse_proto protoreflect.FileDescriptor

var file_expanse_protos_expanse_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x65, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x26, 0x47, 0x65, 0x74, 0x45, 0x78,
	0x70, 0x61, 0x6e, 0x73, 0x65, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x27, 0x47, 0x65, 0x74,
	0x45, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x99, 0x01, 0x0a,
	0x0e, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x86, 0x01, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x73, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f,
	0x6e, 0x74, 0x68, 0x12, 0x2f, 0x2e, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x6d, 0x79, 0x2d, 0x62,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x79, 0x2d, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_expanse_protos_expanse_proto_rawDescOnce sync.Once
	file_expanse_protos_expanse_proto_rawDescData = file_expanse_protos_expanse_proto_rawDesc
)

func file_expanse_protos_expanse_proto_rawDescGZIP() []byte {
	file_expanse_protos_expanse_proto_rawDescOnce.Do(func() {
		file_expanse_protos_expanse_proto_rawDescData = protoimpl.X.CompressGZIP(file_expanse_protos_expanse_proto_rawDescData)
	})
	return file_expanse_protos_expanse_proto_rawDescData
}

var file_expanse_protos_expanse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_expanse_protos_expanse_proto_goTypes = []any{
	(*GetExpansesAmountInCurrentMonthRequest)(nil),  // 0: expanse.GetExpansesAmountInCurrentMonthRequest
	(*GetExpansesAmountInCurrentMonthResponse)(nil), // 1: expanse.GetExpansesAmountInCurrentMonthResponse
}
var file_expanse_protos_expanse_proto_depIdxs = []int32{
	0, // 0: expanse.ExpanseService.GetExpansesAmountInCurrentMonth:input_type -> expanse.GetExpansesAmountInCurrentMonthRequest
	1, // 1: expanse.ExpanseService.GetExpansesAmountInCurrentMonth:output_type -> expanse.GetExpansesAmountInCurrentMonthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_expanse_protos_expanse_proto_init() }
func file_expanse_protos_expanse_proto_init() {
	if File_expanse_protos_expanse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expanse_protos_expanse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expanse_protos_expanse_proto_goTypes,
		DependencyIndexes: file_expanse_protos_expanse_proto_depIdxs,
		MessageInfos:      file_expanse_protos_expanse_proto_msgTypes,
	}.Build()
	File_expanse_protos_expanse_proto = out.File
	file_expanse_protos_expanse_proto_rawDesc = nil
	file_expanse_protos_expanse_proto_goTypes = nil
	file_expanse_protos_expanse_proto_depIdxs = nil
}
